name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: 35.237.191.159
          USERNAME: swapneelrk9
          PORT: 22
          KEY: ${{secrets.SSHKEY}}
        with:
          source: "."
          target: "/var/www/html"